[package]
name = "stable-fs"
version = "0.1.5"
edition = "2021"


[dependencies]
bitflags = "2.2.1"
ic-cdk = "0.7.3"
ic-cdk-macros = "0.6.8"
ic-stable-structures = "0.5.3"
serde = "1.0.160"
serde_bytes = "0.11"
ciborium = "0.2.0"
